version: '3'
services:
  mininet-in-a-container:
    privileged: true
    tty: true
    build:
      context: .
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.x11-unix
      - /lib/modules:/lib/modules
    container_name: mininet
    image: pmanzoni/mininet-in-a-container
  atomix1:
    container_name: atomix1
    image: atomix/atomix:3.1.5
    restart: always
    ports:
      - 5679
    networks:
      network:
        ipv4_address: 172.16.1.2
    hostname: atomix1
    volumes:
      - ~/atomix-cluster/atomix1.conf:/opt/atomix/conf/atomix.
  atomix2:
    container_name: atomix2
    image: atomix/atomix:3.1.5
    restart: always
    ports:
      - 5679
    networks:
      network:
        ipv4_address: 172.16.1.3
    hostname: atomix2
    volumes:
      - ~/atomix-cluster/atomix2.conf:/opt/atomix/conf/atomix.conf
  atomix3:
    container_name: atomix3
    image: atomix/atomix:3.1.5
    restart: always
    ports:
      - 5679
    networks:
      network:
        ipv4_address: 172.16.1.4
    hostname: atomix3
    volumes:
      - ~/atomix-cluster/atomix3.conf:/opt/atomix/conf/atomix.conf
  onos1:
    container_name: onos1
    image: onosproject/onos:2.5.1
    restart: always
    ports:
      - 8181:8181
      - 8101:8101
      - 6653:6653
    networks:
      network:
        ipv4_address: 172.16.1.5
    hostname: onos1
    environment:
      - ONOS_APPS=fwd,openflow
    volumes:
      - ~/atomix-cluster/cluster1.json:/root/onos/config/cluster.json
  onos2:
    container_name: onos2
    image: onosproject/onos:2.5.1
    restart: always
    ports:
      - 8182:8181
      - 8102:8101
      - 6654:6653
    networks:
      network:
        ipv4_address: 172.16.1.6
    hostname: onos2
    volumes:
      - ~/atomix-cluster/cluster2.json:/root/onos/config/cluster.json
  onos3:
    container_name: onos3
    image: onosproject/onos:2.5.1
    restart: always
    ports:
      - 8183:8181
      - 8103:8101
      - 6655:6653
    networks:
      network:
        ipv4_address: 172.16.1.7
    hostname: onos3
    volumes:
      - ~/atomix-cluster/cluster3.json:/root/onos/config/cluster.json
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16