version: '3'
services:
  atomix1:
    container_name: atomix1
    image: atomix/atomix:3.1.5
    restart: always
    ports:
      - 5679
    networks:
      onos:
        ipv4_address: 172.17.0.2
    hostname: atomix1
    command: ["--config","/etc/atomix/conf/atomix.conf","--ignore-resources","--data-dir","/var/lib/atomix/data"]
    volumes:
      - atomix-1.conf:/opt/atomix/conf/atomix.conf
      - /var/lib/atomix/data
  atomix2:
    container_name: atomix2
    image: atomix/atomix:3.1.5
    restart: always
    ports:
      - 5679
    networks:
      onos:
        ipv4_address: 172.17.0.3
    hostname: atomix2
    command: ["--config","/etc/atomix/conf/atomix.conf","--ignore-resources","--data-dir","/var/lib/atomix/data"]
    volumes:
      - atomix-2.conf:/opt/atomix/conf/atomix.conf
      - /var/lib/atomix/data
  atomix3:
    container_name: atomix3
    image: atomix/atomix:3.1.5
    restart: always
    ports:
      - 5679
    networks:
      onos:
        ipv4_address: 172.17.0.4
    hostname: atomix3
    command: ["--config","/etc/atomix/conf/atomix.conf","--ignore-resources","--data-dir","/var/lib/atomix/data"]
    volumes:
      - atomix-3.conf:/opt/atomix/conf/atomix.conf
      - /var/lib/atomix/data
  onos1:
    container_name: onos1
    image: onosproject/onos:2.2.0
    restart: always
    ports:
      - 8181:8181
      - 8101:8101
      - 6653:6653
    networks:
      onos:
        ipv4_address: 172.17.0.5
    hostname: onos1
    volumes:
      - cluster1.json:/root/onos/config/cluster.json
  onos2:
    container_name: onos2
    image: onosproject/onos:2.2.0
    restart: always
    ports:
      - 8182:8181
      - 8102:8101
      - 6654:6653
    networks:
      onos:
        ipv4_address: 172.17.0.6
    hostname: onos2
    volumes:
      - cluster2.json:/root/onos/config/cluster.json
  onos3:
    container_name: onos3
    image: onosproject/onos:2.2.0
    restart: always
    ports:
      - 8183:8181
      - 8103:8101
      - 6655:6653
    networks:
      onos:
        ipv4_address: 172.17.0.7
    hostname: onos3
    volumes:
      - cluster3.json:/root/onos/config/cluster.json
#networks:
#  onos:
#    external: true

