version: "3.3"
services:

  consul:
    image: consul:1.6.0
    command: ["consul","agent","-config-file=/config/consul-single-dc.hcl","-config-dir=/config"]
    volumes:
      - "../consul_config:/config"
    ports:
      - 8500:8500
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  # Define web service and envoy sidecar proxy
  mininet-in-a-container:
    privileged: true
    tty: true
#    build:
#      context: .
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.x11-unix
      - /lib/modules:/lib/modules
    container_name: mininet
    image: pmanzoni/mininet-in-a-container
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    ports:
      - 6555:6555
  web_envoy:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
#    image: nicholasjackson/consul-envoy:latest
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/web_v1.hcl
      CENTRAL_CONFIG: /central_config/web-defaults.hcl
#      CENTRAL_CONFIG: "/central_config/web-defaults.hcl;/central_config/api-defaults.hcl;/central_config/api-v1-defaults.hcl;/central_config/api-v2-defaults.hcl;/central_config/api-router.hcl"
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "web-v1"]
    network_mode: "service:mininet-in-a-container"

  # Define api service and envoy sidecar proxy for version 1 of the service
  onos1:
    container_name: onos1
    image: onosproject/onos:2.5.1
    restart: always
#    environment:
#      - ONOS_APPS=fwd,openflow
    ports:
      - 8181:8181
      - 8101:8101
#      - 6653:6653
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
  payments_proxy:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
#    image: nicholasjackson/consul-envoy:latest
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/payments_v1.hcl
    volumes:
      - "./service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "payments-v1"]
    network_mode: "service:onos1"

  onos2:
    container_name: onos2
    image: onosproject/onos:2.5.1
    restart: always
#    environment:
#      - ONOS_APPS=fwd,openflow
    ports:
      - 8182:8181
      - 8102:8101
#      - 6653:6653
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  onos2_proxy:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
#    image: nicholasjackson/consul-envoy:latest
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/onos2.hcl
    volumes:
      - "./service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "onos2"]
    network_mode: "service:onos2"
  
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
